### ISSUE TITLE
fix: contents

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain-project.github.io#26]
![Screenshot_20191211-112416_Chrome](https://user-images.githubusercontent.com/37016180/70585886-fdb47680-1c08-11ea-8894-ccc7bdb91425.jpg)
![Screenshot_20191211-112301_Chrome](https://user-images.githubusercontent.com/37016180/70585898-0442ee00-1c09-11ea-8e7b-c40195ebf862.jpg)
![Screenshot_20191211-112222_Chrome](https://user-images.githubusercontent.com/37016180/70585904-086f0b80-1c09-11ea-8e4c-54d7d2e22ec9.jpg)

**Comment by cryptozeny** [comment]
`Halving is everything about limiting the total supply`

**Comment by Nugetzrul3** [comment]
https://github.com/sugarchain-project/sugarchain-project.github.io/pull/34

**Comment by cryptozeny** [comment]
fixed closing
