### ISSUE TITLE
domain verification

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain-project.github.io#27]
![image](https://user-images.githubusercontent.com/37016180/70909693-58a6fd00-2051-11ea-9b65-40258887d64f.png)

How come we do not have the verified badge?

**Comment by cryptozeny** [comment]
i tried before, but not worked. i will try it again if i can.

**Comment by Nugetzrul3** [comment]
I asked @itwysgsl, I'll see what he says

**Comment by Nugetzrul3** [comment]
Reason is because email and website domain are different
![9FD9A723-5AD2-4E83-BF23-144CD8ABA7A7](https://user-images.githubusercontent.com/52128634/71009478-43030780-2125-11ea-9cf4-feca3889ff00.jpeg)

**Comment by cryptozeny** [comment]
thanks! i will find a email server if i can.

**Comment by Nugetzrul3** [comment]
If we remove email and leave website, then we can get verified badge

**Comment by cryptozeny** [comment]
![image](https://user-images.githubusercontent.com/37016180/71369538-6975e680-25ee-11ea-82ab-3f72e3bc64e9.png)
it worked thanks!
