### ISSUE TITLE
add: Webwallet & Nodemap

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain-project.github.io#33]
RakutensToday at 10:05 AM
I think we should add the links of Web wallet and node map to the official website

**Comment by volbil** [comment]
Added web wallet https://github.com/sugarchain-project/sugarchain-project.github.io/commit/f63bd64f87a01734a4a8d5a7a0a290b056907fa3

**Comment by cryptozeny** [comment]
awesome!

**Comment by volbil** [comment]
Added explorer https://github.com/sugarchain-project/sugarchain-project.github.io/commit/3a2976cc6fa6e7498f739df7b6858ab1e1fe411e
